### ISSUE TITLE
Support Android TV as a screen saver

### ISSUE THREAD

**Issue by Fleker** [muzei/muzei#281]
It should not be too difficult to extend the mobile app to support Android TV for the screen saver.

**Comment by ianhanniballake** [comment]
Right now there's only one current artwork for each source, which doesn't necessarily lead itself to a screen saver (where you'd probably want multiple pictures from the selected source to cycle through).

**Comment by Fleker** [comment]
I think there is a compelling use case for a TV since it's a great way to
show imagery while it's in a passive view. It may seem a bit bland to only
have a single view, but I think it could be a useful addition without much
extra work.

I'll work on this and do a PR if the user experience is positive.

**Comment by ianhanniballake** [comment]
Oh yeah, definitely have already considered TV as a useful platform. I just think there's some prerequisite thinking about how the API might need to be improved to better support the daydreaming case.

**Comment by ianhanniballake** [comment]
On a positive note: the new API being built has multiple available artwork as a first class concept, which should make doing a slide show through those pictures much more reasonable.

There's still an open issue on how to deal with sources that only have a single artwork and this includes the Featured Art source (which only has today's artwork available).

Having a static image for 24 hours probably isn't the best for a screen saver, but slowly scrolling the artwork back and forth (similar to the screen before you Activate Muzei, minus the blurring/unblurring) might be too distracting compared to a static image. An alternate approach where you move the image just a few pixels every once and a while is probably enough to prevent any kind of burn in, but even that movement might be too noticeable.

**Comment by Fleker** [comment]
A couple of months ago I actually implemented a version of Muzei with DashClock widgets as a screensaver, called [NeoDash](http://github.com/itvlab/neodash).

It does provide something more interesting visually for sources with single artwork, although it doesn't really solve the burn-in issue.

Does Muzei support animated pictures? Maybe a collection of moving images would work better as a screensaver.

**Comment by ianhanniballake** [comment]
Yeah, I'm not entirely sure if burn in is a serious concern, but I'm still not sure how you offer a good experience with just a single image, as will be the default experience with the Featured Art source.

Perhaps a single static artwork that changes once a day is enough (clearly, there is at least some [market for art piece TVs](https://www.engadget.com/2017/09/01/samsung-the-frame-tv-43-inch-first-look/)).

**Comment by ianhanniballake** [comment]
It looks like [Google TV removed the option for third party screen savers](https://www.reviewgeek.com/125089/chromecast-with-google-tv-loses-third-party-screensavers/), so I think the time for Muzei on Android TVs never had its time in the sun.

If this changes, we can reopen this for reconsideration.
