### ISSUE TITLE
Please allow scaling images 

### ISSUE THREAD

**Issue by rijan72** [muzei/muzei#709]
I'm using Samsung's default trash launcher cause as of android 10 3rd party launchers does not support gesture navigation.
Also as I had rebooted my phone previously applied images are no longer centers rather they appear from further left.

I test this app on nova launcher and it worked godly but as mentioned above it lacks gesture navigation support.

Rather than relying on a launcher it would be nice to be able to scale wallpaper from with in the app. It is annoying to be unable to do anything to adjust the wallpaper.

It would be nice if the there was a toggle or check box that allowed users to save the movement of wallpaper inside the app as permanent rather than restoring it back to default when going back to the launcher. 

Other than this one annoyance I am much thankfull toward developers of this app  and it community extensions for this amazing app.

**Comment by ianhanniballake** [comment]
We've covered this request previously in #13, #62, #64, #594, #695, #697, and #698. Muzei doesn't control the position of the wallpaper - that is the launcher's responsibility.

You can see a further discussion of this on #711
