### ISSUE TITLE
Images no longer centered after a reboot

### ISSUE THREAD

**Issue by rijan72** [muzei/muzei#710]
Previously the wallpapers would have been centered on Samsung's launcher but after a reboot the images started appearing from futher left.

I have clear data and cache of both app still the issue continues.

https://drive.google.com/file/d/12u1DhwzZNg2LYmd6d9NGS8ngXDnv8zOL/view?usp=drivesdk

Before the girl in the above video would have been centered like during 00:05 but now the image gets shifted towards left

**Comment by ianhanniballake** [comment]
See the discussion in #711 - Muzei has no control over the centering of the image.
