### ISSUE TITLE
Imporve the "browse source's wallpapers" view

### ISSUE THREAD

**Issue by Lurux** [muzei/muzei#714]
First of all, I'd like to thank you for this amazing, open-source app that you're providing.

### I know this is going to be a long issue for such a small change, but there was a lot to say

Currently, when browsing wallpapers from a specific source, they are sorted by "latest first, oldest last". This may seem logical at first glance, but it causes **several UX and functional problems:**

First of all, the app starts by using the oldest wallpapers, going "up" from there. With sources providing a long stream of images, this means that the user will need to scroll down all the way to the bottom of the list in order to see the "first" images, which isn't very convenient (not to mention that it doesn't feel very natural).

Worse: because the wallpapers are automatically downloaded when they scroll into view, this can lead to situations where **some images are effectively going to be ignored by Muzei:** imagine we do this with a source that provides a long and static stream of images:

- User activates Muzei for the first time, and activates custom source while online. The last item of the list is fetched and used.
- User opens the "browse" page of active source, while online. First few (most recent) items of the list gets fetched.
- User goes offline, then tries to skip an image (if the source allows it), or Muzei tries to load the next one. Since it can't connect to the web, it jumps directly to next available image, which happens to be one of the first few items in the list.
- Next time it tries to load an image (whether online or not), Muzei will continue "upwards" from that last selected image, ignoring everything in between. The ignored images can only be accessed manually.

Considering all of this, I think it would be better and more logical to reverse the sorting of the "browse" view, by showing the oldest images first, *then* the latest ones.

### Further improvements (aka nitpicking)

Along with this change, I think it would make sense to completely hide the non-downloaded images from the list, allowing the user to download them using a dedicated button, or just by scrolling to the bottom of the list.

This would also allow to load images in a sequential and more controlled way; currently, it is possible to end up with **half-loaded images** just because you scrolled a bit too fast in the list, with no real way to fix them. That's a bit annoying...

**Comment by ianhanniballake** [comment]
> First of all, the app starts by using the oldest wallpapers, going "up" from there. With sources providing a long stream of images, this means that the user will need to scroll down all the way to the bottom of the list in order to see the "first" images, which isn't very convenient (not to mention that it doesn't feel very natural).

Actually, the intent is exactly the opposite - the most recently added artwork is on top, thus ensuring that the freshest content is available. Otherwise, if you were to trigger the refresh action (say, via pull to refresh), you might not actually see anything change despite new images actually being loaded.

> Next time it tries to load an image (whether online or not), Muzei will continue "upwards" from that last selected image, ignoring everything in between. The ignored images can only be accessed manually.

This isn't actually how Muzei works. Yes, if you have artwork that won't load (either because you're offline, etc.), they'll get skipped and the 'high water mark' will be updated, but once all images are seen (the high water mark reaches the top), Muzei automatically switches into randomly selecting artwork from any of the available artwork.

> Along with this change, I think it would make sense to completely hide the non-downloaded images from the list, allowing the user to download them using a dedicated button, or just by scrolling to the bottom of the list.

There's no way for Muzei to know what images are already downloaded or not. From Muzei's perspective, all artwork is exactly the same - a URI we can send onto the image loading library to display.

> This would also allow to load images in a sequential and more controlled way; currently, it is possible to end up with half-loaded images just because you scrolled a bit too fast in the list, with no real way to fix them.

Nothing ever stops an image from loading, so you should never see half loaded images. Can you explain what you mean?

**Comment by Lurux** [comment]
> Actually, the intent is exactly the opposite - the most recently added artwork is on top, thus ensuring that the freshest content is available. Otherwise, if you were to trigger the refresh action (say, via pull to refresh), you might not actually see anything change despite new images actually being loaded.

I get that, it makes sense. In that case, I guess we could put the refresh button at the bottom of the list, but I understand why this can be inconvenient too.

> This isn't actually how Muzei works. Yes, if you have artwork that won't load (either because you're offline, etc.), they'll get skipped and the 'high water mark' will be updated, but once all images are seen (the high water mark reaches the top), Muzei automatically switches into randomly selecting artwork from any of the available artwork.

That's odd, this is not what I observed. When offline, Muzei just fails to show a new wallpaper when the top of my source have been reached, even if some previous artwork is already available. It works as intended when online, though.

I just verified that again to make sure, this is the source I'm using: https://f-droid.org/en/packages/net.ebt.muzei.miyazaki/

> There's no way for Muzei to know what images are already downloaded or not. From Muzei's perspective, all artwork is exactly the same - a URI we can send onto the image loading library to display.

Oh wow, really ? Is there not any way to differentiate ? Maybe on the library's side, then ?

> Nothing ever stops an image from loading, so you should never see half loaded images. Can you explain what you mean?

![Screenshot_20210218-110516_Muzei](https://user-images.githubusercontent.com/35870988/108341521-0247c800-71da-11eb-8e86-f369706bbdcb.png)

This happened to me a few times while scrolling a bit too fast on bad wifi. If I were to click on one of these images, it would set an incomplete wallpaper. However, I just noticed that re-opening the app fixes it. I think it isn't really much much of a problem, to be honest :smile:

**Comment by Lurux** [comment]
Closing the issue to clean up.

@ianhanniballake, some of my points still need to be addressed:

> > Once all images are seen (the high water mark reaches the top), Muzei automatically switches into randomly selecting artwork from any of the available artwork.
> 
> That's odd, this is not what I observed. If I click the "next" button while offline, Muzei just fails to show a new wallpaper when the top of my source have been reached, even if some previous artwork is already available. It works as intended once online, though.

I'll investigate this and open an issue if needed.

> > There's no way for Muzei to know what images are already downloaded or not. From Muzei's perspective, all artwork is exactly the same - a URI we can send onto the image loading library to display.
> 
> Oh wow, really ? Is there not any way to differentiate ? Maybe on the library's side, then ?
