### ISSUE TITLE
[Request] Make the new Android 11 zoom feature optional

### ISSUE THREAD

**Issue by d3x7r0** [muzei/muzei#716]
I recently received the update to Android 11 and was surprised to see my background suddenly zoom in and out. I saw that this was implemented on #682. Would it be possible to make this behavior an option instead?

**Comment by ianhanniballake** [comment]
Sorry, but no. Muzei's integration with the Android APIs provided to live wallpapers are not optional on any API level, Android 11 included.

**Comment by d3x7r0** [comment]
Sorry. I didn't realize this was a new Google mandated feature because I'm not a full time developer myself. Thank you for your kind response and sorry I'm really sorry asked.

**Comment by ianhanniballake** [comment]
It's not a problem to ask. It seems like others have already asked for an Android wide feature to disable the wallpaper zoom effect on the official issue tracker in [this issue](https://issuetracker.google.com/issues/168097088) and [this issue](https://issuetracker.google.com/issues/175337133).

If such a feature was implemented, Muzei would already support it out of the box as Muzei is just following the signals the framework is sending us - it would be up to the Android framework to *not* send those signals based on a setting on their side.

**Comment by d3x7r0** [comment]
Fair enough. I was completely unaware of this behavior and just decided to ask.

If google mandates that you respect the new flag/hint/callback then nothing to do I guess. I was just asking if it was possible to make the response to that callback optional since I couldn't find any documentation other than that the hint exists but, as I mentioned, I'm not a full time android developer and am honestly not particularly well versed in reading android docs. 😅

**Comment by jeslinmx** [comment]
Sorry to revive an old thread but it seems like a relevant existing issue; I'd like to clarify if Google's mandate also extends to limiting the customizability of the zoom level. Since #682 and #692 imply that the zoom value is at the discretion of the developer (and can even be negative), would it be permitted to respect the callback with a user-customizable zoom level, defaulting to stock Android 11+ behavior but able to be set to 0 or negative?
