### ISSUE TITLE
viewBinding in fragments

### ISSUE THREAD

**Issue by enriquebautista** [muzei/muzei#720]
Fragments in Muzei don't clean up binding reference in onDestroyView()

Android docs:
Fragments outlive their views. Make sure you clean up any references to the binding class instance in the fragment's onDestroyView() method.

[See architecture sample](https://github.com/android/architecture-components-samples/blob/main/ViewBindingSample/app/src/main/java/com/android/example/viewbindingsample/BindFragment.kt)

**Comment by ianhanniballake** [comment]
This is only true if the Fragment is put on the Fragment back stack. In every other case, the Fragment and the Fragment view lifecycle is the same.

That being said, this does affect the `ArtDetailFragment`, so we can fix that.
