### ISSUE TITLE
AutoClearedValue

### ISSUE THREAD

**Issue by enriquebautista** [muzei/muzei#721]
what is the difference between your AutoClearedValue and that of Architecture-components ?

https://github.com/android/architecture-components-samples/blob/main/GithubBrowserSample/app/src/main/java/com/android/example/github/util/AutoClearedValue.kt

**Comment by ianhanniballake** [comment]
There's no difference. I wrote both of them. See [my PR there](https://github.com/android/architecture-components-samples/pull/785) and [my commit here](https://github.com/muzei/muzei/commit/ece4278648e2a142084088e2e12a7af3ef115550).
