### ISSUE TITLE
Empty sources

### ISSUE THREAD

**Issue by rtaupe** [muzei/muzei#726]
On my Fairphone 3 with Android 10, Muzei only shows "The Starry Night" by Van Gogh.
The "Featured art" source contains only this single image, and other sources contain no images at all (for example the National Geographic extension which I have installed).
![Screenshot_20210418-161616](https://user-images.githubusercontent.com/1563953/115148973-2dc42300-a062-11eb-97eb-326f585b4fd3.png)
![Screenshot_20210418-161634](https://user-images.githubusercontent.com/1563953/115148976-30267d00-a062-11eb-9795-ad40c7a665a0.png)

**Comment by ianhanniballake** [comment]
Are you installing Muzei from the [Google Play Store](https://play.google.com/store/apps/details?id=net.nurik.roman.muzei)? That is the only place to install a supported version of Muzei. Any other version is **not** built by Muzei.

**Comment by rtaupe** [comment]
I had the version from F-Droid. After deleting the app's storage and re-installing it from Google Play, now it works. Thanks!
