### ISSUE TITLE
Can't set: App isn't installed 

### ISSUE THREAD

**Issue by mizzunet** [muzei/muzei#729]
When I try to say Activate

![Screenshot_20210520-073741](https://user-images.githubusercontent.com/10193999/118908044-43b55400-b93e-11eb-9202-fad18d20bcf4.png)

 When I try Wallpaper app

![Screenshot_20210520-070639](https://user-images.githubusercontent.com/10193999/118908078-5039ac80-b93e-11eb-8a9f-e8df4728e84e.png)

Here's log
https://transfer.sh/IFu1M/2021-05-20-07-36-07.txt

**Comment by ianhanniballake** [comment]
It looks like your device is completely messed up and, unfortunately, there's nothing Muzei can do about that. 😞

The reason you get the popup message in the first place is that your Android system hasn't been configured to support live wallpapers correctly. Are you running some sort of custom ROM that may have purposefully not included the app that handles the live wallpaper picker?

The wallpaper picker is part of the Android system. As you might imagine, that means Muzei has no control over that screen. If you're seeing Muzei on that screen at all, that means that it is indeed detecting it as a valid live wallpaper. My suspicion is that the "App isn't installed" isn't referring to Muzei, but referring to the live wallpaper picker APK that for some reason isn't included on your device.

**Comment by mizzunet** [comment]
> It looks like your device is completely messed up and, unfortunately, there's nothing Muzei can do about that. 😞
> 
> The reason you get the popup message in the first place is that your Android system hasn't been configured to support live wallpapers correctly. Are you running some sort of custom ROM that may have purposefully not included the app that handles the live wallpaper picker?
> 
> The wallpaper picker is part of the Android system. As you might imagine, that means Muzei has no control over that screen. If you're seeing Muzei on that screen at all, that means that it is indeed detecting it as a valid live wallpaper. I suspect that the "App isn't installed" isn't referring to Muzei, but referring to the live wallpaper picker APK that for some reason isn't included on your device.

My bad, I had debloated apps which led Live Wallpaper app disabled, I enabled it and tried again. Now working. Great, thanks :)
