### ISSUE TITLE
Feature Request: Configure watchface font on Wear OS app

### ISSUE THREAD

**Issue by RStene** [muzei/muzei#740]
Hi,

Is there any chance that the watchface font could be made user-configurable? I love Muzei and its companion wearable app, but the font on the clock is quite a bit more bubbly than I'd like. I'm hoping for configuration similar to what we already get with complications, where a user could select between the existing default, Nunito Bold, and something else like Roboto (with a similarly-bolded weight).

Thanks for all the work you do on this app--it really is great.

**Comment by ianhanniballake** [comment]
We've discussed this previously in #108 - one of the things Muzei's Wear integration supports out of the box is allowing Muzei to be used as the background of other watch faces via those same complications APIs.
