### ISSUE TITLE
Allow tasker actions to change Muzei Source

### ISSUE THREAD

**Issue by ksrikanthcnc** [muzei/muzei#753]
Adding this action would give possibility to create a tasker action which can pick random source from installed multiple sources

**Comment by ianhanniballake** [comment]
Muzei's Tasker integration already supports two kinds of actions:
- Next Artwork
- Selecting a specific source of your choosing

When you configure the tasker action, you choose exactly which of those actions you want to trigger when the action fires.

**Comment by ksrikanthcnc** [comment]
I meant a tasker action to select the artwork (where artwork is dynamic-variable, not through one-time static configuration).
I tried creating a tasker task, which selects a random source from the installed sources, but since tasker action's plugin doesnt allow changing source dynamically, I was not abl to achive this.

**Comment by ksrikanthcnc** [comment]
Can Muzei provide the list of add-ons/plug-ins, along with the package name (ComponentName), so that in Tasker, we can use this list and select one of the plug-in to be the active source ?

**Comment by ianhanniballake** [comment]
That's how Muzei's Tasker integration works right now - when you set up a task using Muzei's Tasker plugin, you select which source you want to switch to when that task is triggered.

You can already, within Tasker itself, [run a random task from a list](https://www.reddit.com/r/tasker/comments/3e83j6/can_a_profile_trigger_a_random_task/). The [suggestion here](https://www.reddit.com/r/tasker/comments/3e83j6/comment/ctchyie) and [accompanying Task screenshot](https://i.imgur.com/ZmExa3N.jpg) worked perfectly for me:

1. Set up a Task for each Muzei source you want to add to your pool of random Muzei sources to switch between
2. Set up a task as per [this screenshot]([accompanying Task screenshot](https://i.imgur.com/ZmExa3N.jpg)) which randomly picks one of those tasks to run

**Comment by ksrikanthcnc** [comment]
Thanks, this serves the purpose of changing muzei source. But it would be easier if we can assign the muzei source using a variable, (with values like com.b_lam.resplash, in.nerd_is.wa_11_h_a, ...).
And also it would be great if muzei itself provides the list of its compatible plug-ins to Tasker, which we can then use to set preferred source, without the need of separate tasks (as you suggested) or manually filled package names.
