### ISSUE TITLE
Allow tasker actions to change Muzei Source

### ISSUE THREAD

**Issue by ksrikanthcnc** [muzei/muzei#754]
I meant a tasker action to select the artwork (where artwork is dynamic-variable, not through one-time static configuration).
I tried creating a tasker task, which selects a random source from the installed sources, but since tasker action's plugin doesn't allow changing source dynamically, I was not able to achieve this.

_Originally posted by @ksrikanthcnc in https://github.com/muzei/muzei/issues/753#issuecomment-1061350415_

**Comment by ianhanniballake** [comment]
Let's keep the conversation on the original issue.
