### ISSUE TITLE
Add get it on F-Droid badge

### ISSUE THREAD

**Issue by PanderMusubi** [muzei/muzei#755]
Please add a get it on F-Droid badge to:
- https://github.com/muzei/muzei/blob/main/README.md
- https://muzei.co/

See also https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md or let me know if you need help with this.

**Comment by sokai** [comment]
Dup of #737(?)

**Comment by ianhanniballake** [comment]
Yep, Google Play remains the only place to get Muzei from: any builds you see on F-Droid are **not** created by, maintained by, or supported by anyone associated with Muzei.
