### ISSUE TITLE
Possible bug: "autoRevokePermissions" declared , but it won't do anything...

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [muzei/muzei#760]
Sadly this attribute won't do anything :
https://github.com/muzei/muzei/blob/main/main/src/main/AndroidManifest.xml#L52
https://developer.android.com/guide/topics/manifest/application-element

The reason:
https://developer.android.com/reference/android/R.attr.html#autoRevokePermissions

"No longer used. Declaring this does nothing"

So, does it do anything, or not?
If so, what would it do, and for which Android versions?

**Comment by ianhanniballake** [comment]
It still does something on API 30 (when it wasn't deprecated) as per [the documentation](https://developer.android.com/about/versions/11/privacy/permissions#auto-reset).

**Comment by AndroidDeveloperLB** [comment]
@ianhanniballake The link you've provided doesn't mention this at all.
Where do you see on the docs that it's supported on API 30? And what do you see an explanation about what it does?
Why isn't it also documented in the manifest website?
And why was it deprecated so quickly for something that seems to me quite useful?
