### ISSUE TITLE
navigation bar color issue

### ISSUE THREAD

**Issue by onlymash** [muzei/muzei#763]
When muzei is in the background, the system theme is switched from light to dark, and then open muzei, the color of the navigation bar is still white

Muzei version: 3.5.0-alpha1
Android version: 12L
![Screenshot_20220903-195424_Muzei](https://user-images.githubusercontent.com/5838634/188269367-91875409-38cc-4658-b3bb-0fb3996493ab.png)

**Comment by ianhanniballake** [comment]
I was able to track down the logic error in Muzei where we were setting the navigation bar color and fix it. It'll be available in Muzei 3.5.0 Alpha 2. Thanks for pointing this out!
