### ISSUE TITLE
[Android 12]Dynamic color not work

### ISSUE THREAD

**Issue by onlymash** [muzei/muzei#764]
When using muzei to set the wallpaper for the first time, the system can get the color from the wallpaper, and when muzei switches to the next wallpaper, the system color does not change.
ROM: LineageOS 19.1/Android 12L
App: 3.5.0 Alpha 2

**Comment by ianhanniballake** [comment]
Muzei already [notifies the system](https://github.com/muzei/muzei/blob/0d0cb3f15cadcbaa23f7b1e5edf20952ee57e6d4/main/src/main/java/com/google/android/apps/muzei/MuzeiWallpaperService.kt#L245) immediately when the wallpaper changes, but when that color is applied is not in Muzei's control.

Android 12L only reloads the wallpaper colors after you turn your screen off and back on again specifically to prevent issues with [crashing or restarting apps when the wallpaper colors change](https://www.xda-developers.com/android-12-game-crashing-automated-wallpapers/).

Do you see the colors update if you turn your screen off and then back on?

**Comment by onlymash** [comment]
Thanks for the info, indeed the color changes after turning the screen off and on
