### ISSUE TITLE
Very rough experience when image is changed and gboard active

### ISSUE THREAD

**Issue by xandro0777** [muzei/muzei#765]
I use gboard and whenever the image+theme happens to change while gboard is active the user experience is pretty horrible. At first I thought gboard crashed.. well maybe it did: the virtual keyboard disappeared, everything in the app was in total disarray for a little while, then keyboard reappeared in totally different appearance. Someone who types almost blindly may hit some other button instead of the expected character because all elements move back and forth.

It might be a good idea to delay changing the theme in some situations? Is there some setting to influence this?

**Comment by ianhanniballake** [comment]
What Android version are you on? Android 12 has a [known issue with wallpaper changes restarting all apps](https://www.xda-developers.com/android-12-game-crashing-automated-wallpapers/) that has already been fixed in Android 12L (something we talked about in #764 just yesterday).

Muzei can't do anything about this, unfortunately.

**Comment by ianhanniballake** [comment]
Let us know if you are seeing this on some version of Android _other_ than Android 12 and we can reopen this to take a look.

**Comment by xandro0777** [comment]
Don't have another version to try. However, given that Android 12 will be pretty widespread for a while, how about implementing some workaround?

Possibly:
* switch to next image only on user request (button in notification)
* switch image only when no App is running in the foreground

I think both would be nice to have even without this bug.. should I open separate tickets for those?

**Comment by xandro0777** [comment]
It is Android 12, Realme flavor. Haven't noticed that issue in any other apps so far so it seems to be something special to the Google keyboard.

Is there any way to control how often the wallpaper is changed? That would help debugging the issue.
