### ISSUE TITLE
Request: before enabling the live-wallpaper, also allow to import the current wallpaper

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [muzei/muzei#770]
Also show how to do it for when targeting API 33, because currently it seems it's not allowed due to a bug:
https://issuetracker.google.com/issues/237124750

**Comment by ianhanniballake** [comment]
Since Muzei targets API 33, this is infeasible.

Nor would we do this anyways - Muzei is purposefully unaware of any of its sources, including its included sources.

**Comment by AndroidDeveloperLB** [comment]
Why is it infeasible?
You can add the MANAGE_EXTERNAL_STORAGE permission on API 33 instead of the READ_EXTERNAL_STORAGE permission.

Talking with the policy team on the Play Store, they failed to even give me explanation of what I can use to do it. They still think I can do it with MediaStore API .

Do you know perhaps how I can use this API (of getting the current wallpaper) without using MANAGE_EXTERNAL_STORAGE , yet targeting API 33?
