### ISSUE TITLE
A way to select the picture alignment with user pictures

### ISSUE THREAD

**Issue by Can-chan** [muzei/muzei#780]
For some reason, muzei doesn't center crop when using the "My Pictures" source in some devices (they always scroll to the left), a way to select the picture alignment would be appreciated (left, right or center)

For the record, phones like the ones from samsung do center them, but both my Huawei and TCL phones don't

**Comment by ianhanniballake** [comment]
See #711 - the reason you are seeing different behavior is because this is controlled by your launcher, not by Muzei.
