### ISSUE TITLE
App not updating wallpaper, domain is down

### ISSUE THREAD

**Issue by arkpope** [muzei/muzei#791]
Hi,

Noticed that the app is not working. muzei.co returns a 404?

**Comment by romannurik** [comment]
Hi there, yes — we're working through a major issue with the GCP project. No current timeline for a fix but we're on it.

**Comment by arkpope** [comment]
Thanks for the update Roman! Good luck and please let us know if there is anything we can do to help!

**Comment by arkpope** [comment]
Back online. Thank you!
