### ISSUE TITLE
Question: is it possible to use Vulkan instead of OpenGL in the live wallpaper?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [muzei/muzei#795]
I've noticed it uses OpenGL.
Is it possible to do the same, but using Vulkan, instead?

I've tried to search about this, but didn't find any tutorial of how to have a live wallpaper with Vulkan, showing an image that can be horizontally scrolled.

I can't even find a decent one with OpenGL.
Can you please offer some guidance of how&what to extract what's important from here, to start a new minimalized app with just this functionality (no need for the blurring and all the settings) ?

**Comment by ianhanniballake** [comment]
While technically possible, given that Vulkan only has C++ APIs, this wouldn't be anything we would ever attempt or recommend.
