### ISSUE TITLE
Play Store not updated 

### ISSUE THREAD

**Issue by loki666** [muzei/muzei#801]
The latest version from the Google Play Store is more than 2 years old and can't be installed anymore.

I don't see an APK in the releases artifacts either.

Is Muzei meant to be only distributed via F-Droid ?

**Comment by ianhanniballake** [comment]
Have you considered joining Muzei's [open beta](https://play.google.com/apps/testing/net.nurik.roman.muzei)? That's where we've been releasing new builds as we prepare for the next major release (which is indeed coming soon).

**Comment by loki666** [comment]
> Have you considered joining Muzei's [open beta](https://play.google.com/apps/testing/net.nurik.roman.muzei)? That's where we've been releasing new builds as we prepare for the next major release (which is indeed coming soon).

I did, but open beta is currently full, so I can't join.
I guess I'll have to wait for the release

Thanks

**Comment by ianhanniballake** [comment]
I've expanded the number of open beta testers. Please try to join again.

**Comment by loki666** [comment]
could join thanks
