### ISSUE TITLE
Random isn't so random

### ISSUE THREAD

**Issue by pwd-github** [muzei/muzei#802]
I have Muzei set up on three devices and the three devices use the same images, I copy them across to each device using SyncThing. So it's really nice to see the images on all devices, but there's a slight problem. While I love that Muzei goes through the new pictures before going back to being random, it's not actually picking from the whole pool. I'm seeing the same images used on all devices and out of a pool of near 1500 pictures, I shouldn't be noticing the same pictures being used. Is there anyway to improve this?

**Comment by ianhanniballake** [comment]
> While I love that Muzei goes through the new pictures before going back to being random, it's not actually picking from the whole pool.

Muzei shows pictures in the exact order that your source adds them to Muzei. Only after every picture is seen does Muzei switch to a shuffle mode.

It sounds like what you're experiencing is just that the SyncThing source has added the pictures in the exact same order on both devices and you're still going through those pictures for the very first time? If so, what you're seeing is expected.

You can switch to the shuffle mode by tapping on 'Browse', then selecting the topmost image - that'll mark that the last image is loaded, which should mean the next artwork you swap to will be a random one.

**Comment by pwd-github** [comment]
I'm definitely seeing something similar to what you described, but when it gets to shuffling, it seems to be only a small subset of the 1500 wallpapers

**Comment by ianhanniballake** [comment]
We've switched to using the Kotlin standard library `Random` instead of Android's `java.util.Random` for the next Muzei release, so we'll see if that helps.

**Comment by pwd-github** [comment]
> We've switched to using the Kotlin standard library `Random` instead of Android's `java.util.Random` for the next Muzei release, so we'll see if that helps.

Thank you so much!
