### ISSUE TITLE
duplicate class error in androidx.wear and com.oogle.support.wearable. any help?

### ISSUE THREAD

**Issue by pravinGithubb** [muzei/muzei#804]
Duplicate class android.support.wearable.authentication.IAuthenticationRequestCallback found in modules wear-phone-interactions-1.0.1-runtime (androidx.wear:wear-phone-interactions:1.0.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.authentication.IAuthenticationRequestCallback$Stub found in modules wear-phone-interactions-1.0.1-runtime (androidx.wear:wear-phone-interactions:1.0.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.authentication.IAuthenticationRequestCallback$Stub$Proxy found in modules wear-phone-interactions-1.0.1-runtime (androidx.wear:wear-phone-interactions:1.0.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.authentication.IAuthenticationRequestService found in modules wear-phone-interactions-1.0.1-runtime (androidx.wear:wear-phone-interactions:1.0.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.authentication.IAuthenticationRequestService$Stub found in modules wear-phone-interactions-1.0.1-runtime (androidx.wear:wear-phone-interactions:1.0.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.authentication.IAuthenticationRequestService$Stub$Proxy found in modules wear-phone-interactions-1.0.1-runtime (androidx.wear:wear-phone-interactions:1.0.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationData found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationData$1 found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationData$Builder found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationData$ComplicationType found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationData$ImageStyle found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationProviderInfo found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationProviderInfo$1 found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationText found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationText$1 found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationText$TimeDifferenceBuilder found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationText$TimeDifferenceStyle found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationText$TimeFormatBuilder found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationText$TimeFormatStyle found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationTextTemplate found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationTextTemplate$1 found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.ComplicationTextTemplate$Builder found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.IComplicationManager found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.IComplicationManager$Stub found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.IComplicationManager$Stub$Proxy found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.IComplicationProvider found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.IComplicationProvider$Stub found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.IComplicationProvider$Stub$Proxy found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.IProviderInfoService found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.IProviderInfoService$Stub found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.IProviderInfoService$Stub$Proxy found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.TimeDependentText found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.TimeDifferenceText found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.TimeDifferenceText$1 found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.TimeDifferenceText$2 found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.TimeFormatText found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.complications.TimeFormatText$1 found in modules watchface-complications-data-1.1.1-runtime (androidx.wear.watchface:watchface-complications-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.notifications.IBridgingManagerService found in modules wear-phone-interactions-1.0.1-runtime (androidx.wear:wear-phone-interactions:1.0.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.notifications.IBridgingManagerService$Stub found in modules wear-phone-interactions-1.0.1-runtime (androidx.wear:wear-phone-interactions:1.0.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.notifications.IBridgingManagerService$Stub$Proxy found in modules wear-phone-interactions-1.0.1-runtime (androidx.wear:wear-phone-interactions:1.0.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.watchface.IWatchFaceService found in modules watchface-data-1.1.1-runtime (androidx.wear.watchface:watchface-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.watchface.IWatchFaceService$Stub found in modules watchface-data-1.1.1-runtime (androidx.wear.watchface:watchface-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.watchface.IWatchFaceService$Stub$Proxy found in modules watchface-data-1.1.1-runtime (androidx.wear.watchface:watchface-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.watchface.WatchFaceStyle found in modules watchface-data-1.1.1-runtime (androidx.wear.watchface:watchface-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.watchface.accessibility.AccessibilityUtils found in modules watchface-data-1.1.1-runtime (androidx.wear.watchface:watchface-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.watchface.accessibility.ContentDescriptionLabel found in modules watchface-data-1.1.1-runtime (androidx.wear.watchface:watchface-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)
Duplicate class android.support.wearable.watchface.accessibility.ContentDescriptionLabel$1 found in modules watchface-data-1.1.1-runtime (androidx.wear.watchface:watchface-data:1.1.1) and wearable-2.9.0-runtime (com.google.android.support:wearable:2.9.0)

Go to the documentation to learn how to Fix dependency resolution errors.

**Comment by ianhanniballake** [comment]
This is expected right now while we rebuild the Wear app.
