### ISSUE TITLE
Background not-visible in App Drawer One UI 6

### ISSUE THREAD

**Issue by emavgl** [muzei/muzei#805]
Hi there, 

My phone (Samsung A52s) recently updated to the latest One UI 6. Muzei still works perfectly, except that the wallpaper does not show in the App Drawer, but rather some pixelate blue background. I am not sure if this is issue with One UI 6 only, or Muzei can do something as workaround.

See the image attached to better understand the problem.

![example](https://github.com/muzei/muzei/assets/6958722/a614cbfd-4eed-48c6-9701-722df2484919)

**Comment by ianhanniballake** [comment]
Muzei does not even know that the app drawer of your launcher is open, so this is definitely something specific to your launcher. Consider trying launchers like [Action Launcher](https://play.google.com/store/apps/details?id=com.actionlauncher.playstore) or [Nova Launcher](https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher) if you want launchers that have more customization support (and better support for live wallpapers like Muzei).
