### ISSUE TITLE
Destroys and rebuilds the activity when setting the wallpaper on a android14 mobile device

### ISSUE THREAD

**Issue by zhukunlun1** [muzei/muzei#806]
When I set the wallpaper on my Android14 mobile device, I find that the activity(MainActivity) gets destroyed and rebuilt, there is an anomaly in the lifecycle as it doesn't go through the rebuild lifecycle before Android 13

**Comment by ianhanniballake** [comment]
Android's Material You theming pulling colors from the wallpaper [does have an effect on other apps](https://www.xda-developers.com/android-12-game-crashing-automated-wallpapers/). That isn't unique to Muzei.
