### ISSUE TITLE
[Feature Request] Allow use custom time

### ISSUE THREAD

**Issue by GreenArchiveForever** [muzei/muzei#808]
hi please consider allow user to use custom time for automatically changing wallpaper

**Comment by ianhanniballake** [comment]
As explained in the bottom of the Auto Advance settings:

> For exact control over what triggers your wallpaper to change, use the 'Next artwork' action available in [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm) under Plugin -> Muzei and disable auto advance here.

Tasker already allows you to trigger a change in wallpaper at a specific time of day, when you get home, or a variety of other triggers, thus giving you full control over exactly when Muzei automatically goes to the next wallpaper.

There's no plans to support any controls directly in Muzei beyond what is available now.
