### ISSUE TITLE
Wallpapers working only partially on /e/OS

### ISSUE THREAD

**Issue by Rik44444** [muzei/muzei#809]
When using Muzei on /e/OS, wallpapers only work partially.
Regular wallpapers fill the entire screen + they also appear on the background of the Widget drawer all the way on the left of /e/OS.
But when using Muzei the area behind the 4 apps on the bottom in /e/OS remains the 'old color' and not the new color of the Muzei wallpaper. Same for the widget drawer, it remains the 'old' colors. See 2 screenshots below.

See also: https://gitlab.e.foundation/e/backlog/-/issues/7589 

![image](https://github.com/muzei/muzei/assets/42555414/eea7547e-c2ee-40db-bd59-5cbb72eca93f)

![image](https://github.com/muzei/muzei/assets/42555414/999e324c-ae7b-439a-a398-307dde259e41)

**Comment by ianhanniballake** [comment]
Muzei is a live wallpaper app. It doesn't control what parts of the screen the wallpaper is shown on, nor does it know if a widget drawer is open or not - that's all something your launcher or the OS controls.

You could try using a third party launcher like [Action Launcher](https://play.google.com/store/apps/details?id=com.actionlauncher.playstore) or [Nova Launcher](https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher) if you want to see what the experience is in another launcher.
