### ISSUE TITLE
Wallpaper Unblur Delay

### ISSUE THREAD

**Issue by cybr47** [muzei/muzei#810]
I wanted to make Muzei work like OnePlus's canvas wallpaper and make the lockscreen blur and keep the home screen unblurred. So it would transition from blurred screen to the home screen's unblurred wallpaper but I noticed that there is a delay in wallpaper being unblurred when I go from lockscreen to home screen. Could this delay time be decreased?

https://github.com/muzei/muzei/assets/81064836/fec09f86-17b9-424f-933d-41a738f96b3e

**Comment by ianhanniballake** [comment]
Muzei starts the transition as soon as we receive the device unlock broadcast from the system.

Unfortunately, Muzei isn't in control over how long it takes for the OS to deliver that - system broadcasts are a single queue on Android, so they can back up depending on what else is going on.
