### ISSUE TITLE
Gestures not working on OneUI 2.0

### ISSUE THREAD

**Issue by NekoMimiOfficial** [muzei/muzei#812]
Device: Samsung J6 2018
Android: 10
Launcher: OneUI home

I'm able to have the gestures work on other launchers (kvaesitso) however they don't seem to work on the lock screen neither OneUI home

**Comment by ianhanniballake** [comment]
See #603, #646, #671, and #699:

> The Double Tap gesture relies on the launcher implementing the `COMMAND_TAP` API. If Muzei's double tap works in third party launchers such as Action Launcher or Nova Launcher, then you should contact Samsung to have them fix their launcher.
