### ISSUE TITLE
Bug : Black screen when uploading pictures 

### ISSUE THREAD

**Issue by eo2000** [muzei/muzei#814]
Description of the bug:
When uploading photos for the wallpaper, the wallpaper is reloaded with a black screen when the device is unlocked. 

How to reproduce:
1. Open Muzei App.
2. Click on sources.
3. Click on My Photos
4. Upload photos 
5. Click the tick to confirm 
6. Lock phone
7. Unlock phone

Actual behaviour: 
<img width="298" alt="Screenshot 2024-04-07 at 3 32 23 PM" src="https://github.com/SOEN345-WINTER2024/discussion/assets/116772744/d6a08b6b-8b10-46db-a47b-33762bbec680">

Expected behaviour: 
The wallpaper should be the photos selected, not a black screen.

Device Model: Pixel 6 API 27
Android Version: Android 8.1 
App version: v3.5.0

**Comment by ianhanniballake** [comment]
When you added the photos to the My Photos source, did you see them in the settings screen for My Photos immediately after adding them?

When you hit the back button directly after adding the images to the My Photos source (i.e., when you are on the Sources screen), do you see one of the images in the 'My Photos' card on that screen? If you tap the 'Browse' button on that "My Photos" card, do you see your images on that screen?

**Comment by ianhanniballake** [comment]
Let us know if you have any additional information as requested above.
