### ISSUE TITLE
Muzei API issue when running on Android 14+

### ISSUE THREAD

**Issue by scubajeff** [muzei/muzei#816]
I have an [app](https://github.com/scubajeff/lespas) working as Muzei artwork provider using Muzei API. After the latest upgrade of Muzei app which target API 34, when user clicking the artwork title, it won't launch my app anymore. I got "Background activity launch blocked!" message showing in logcat. Is this related to this [API 34 behavior change](https://developer.android.com/about/versions/14/behavior-changes-14#background-activity-restrictions)?

**Comment by ianhanniballake** [comment]
Good catch! We've fixed this internally and will release a Muzei 3.6.1 with the fix.
