### ISSUE TITLE
Opening external sources links seems to be broken

### ISSUE THREAD

**Issue by gferry** [muzei/muzei#817]
Hi there,

I'm a happy Muzei user, combined with ReSplash plugin :)
Prior to the recent beta release, I was able to click the image title, and consult the source page on Unsplash website.
It seems I cannot do this anymore (click is ineffective) : is it a regression in ReSplash, or Muzei ?

Target version (beta) : 3.6.1

Thanks in advance,
Guillaume.

**Comment by gferry** [comment]
I'll rollback to the stable version and see if the bug if also present.

**Comment by gferry** [comment]
Ok, it seems to be fixed in the latest version, thanks :)

**Comment by gferry** [comment]
Done

**Comment by ianhanniballake** [comment]
Yep, dup of #816
